apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: in-memory
    type: chache-memory
spec:
  containers:
    - name: redis-container
      image: redis


# CMD --> kubectl create -f redis-pod.yaml
# CMD -->  kubectl get pods